/**
 * @generated by code-mode sdk-gen — shared runtime invoker.
 * Spawns the relevant MCP server on demand, runs one tool call, returns the
 * parsed result. Cached per-process so repeated calls reuse the same
 * transport.
 *
 * DO NOT EDIT — overwritten on every reindex.
 */

import serversJson from "./_servers.json" with { type: "json" };

interface RegistryEntry {
  transport: "stdio" | "http";
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
}

const registry = serversJson as unknown as Record<string, RegistryEntry>;

interface ClientLike {
  callTool(params: { name: string; arguments?: Record<string, unknown> }): Promise<unknown>;
  close(): Promise<void>;
}

const cache = new Map<string, Promise<ClientLike>>();

async function getClient(server: string): Promise<ClientLike> {
  const existing = cache.get(server);
  if (existing) return existing;
  const entry = registry[server];
  if (!entry) throw new Error(`[code-mode] unknown MCP server: ${server}`);
  const p = (async (): Promise<ClientLike> => {
    const [{ Client }, stdio, http] = await Promise.all([
      import("@modelcontextprotocol/sdk/client/index.js"),
      import("@modelcontextprotocol/sdk/client/stdio.js"),
      import("@modelcontextprotocol/sdk/client/streamableHttp.js"),
    ]);
    const client = new Client(
      { name: "code-mode-runtime", version: "0.0.0" },
      { capabilities: {} },
    );
    let transport: unknown;
    if (entry.transport === "stdio") {
      if (!entry.command) throw new Error(`[code-mode] stdio server ${server} missing command`);
      transport = new stdio.StdioClientTransport({
        command: entry.command,
        args: entry.args ?? [],
        env: entry.env ? { ...(process.env as Record<string, string>), ...entry.env } : undefined,
        stderr: "inherit",
      });
    } else {
      if (!entry.url) throw new Error(`[code-mode] http server ${server} missing url`);
      transport = new http.StreamableHTTPClientTransport(new URL(entry.url));
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (client as any).connect(transport);
    return client as unknown as ClientLike;
  })();
  cache.set(server, p);
  return p;
}

export async function callTool<T = unknown>(
  server: string,
  tool: string,
  args: Record<string, unknown>,
): Promise<T> {
  const client = await getClient(server);
  const result = await client.callTool({ name: tool, arguments: args });
  return (result as { structuredContent?: unknown }).structuredContent as T ??
    (result as T);
}

export async function closeAll(): Promise<void> {
  const clients = Array.from(cache.values());
  cache.clear();
  await Promise.allSettled(
    clients.map(async (p) => {
      try {
        const c = await p;
        await c.close();
      } catch {
        /* best-effort */
      }
    }),
  );
}
