/**
 * @generated by code-mode sdk-gen from MCP server "github" at 2026-04-13T00:00:00.000Z.
 * DO NOT EDIT — this file is overwritten on every reindex.
 */
import { callTool } from "./_client.ts";

export interface CreateIssueArgs {
  /** Issue title */
  title: string;
  body?: string;
  labels?: string[];
  priority?: "low" | "medium" | "high";
  assignee?: {
    login: string;
    id?: number;
  };
}

export interface CreateIssueResult {
  number: number;
  url: string;
}

/** Create a GitHub issue. */
export async function createIssue(args: CreateIssueArgs): Promise<CreateIssueResult> {
  return callTool("github", "create_issue", args as unknown as Record<string, unknown>) as Promise<CreateIssueResult>;
}

export type PingArgs = Record<string, unknown>;

export type PingResult = unknown;

/** Health ping. */
export async function ping(args: PingArgs): Promise<PingResult> {
  return callTool("github", "ping", args as unknown as Record<string, unknown>) as Promise<PingResult>;
}
