import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { emitGeneratedSdks, listGeneratedFiles } from "../../src/sdk-gen/emit.ts";
import type { IntrospectResult } from "../../src/sdk-gen/introspect.ts";

const FIXED_NOW = () => new Date("2026-04-13T00:00:00.000Z");

function buildResult(name: string): IntrospectResult {
  return {
    spec: {
      name,
      transport: "stdio",
      command: "bun",
      args: ["run", "server.ts"],
      sourcePath: "/fake/.mcp.json",
    },
    ok: true,
    tools: [
      {
        name: "create_issue",
        description: "Create an issue",
        inputSchema: {
          type: "object",
          properties: {
            title: { type: "string" },
            priority: { enum: ["low", "medium", "high"] },
          },
          required: ["title"],
        },
        outputSchema: {
          type: "object",
          properties: { number: { type: "integer" } },
          required: ["number"],
        },
      },
    ],
  };
}

describe("sdk-gen/emit", () => {
  let tmpRoot: string;
  let sdksDir: string;

  beforeEach(() => {
    tmpRoot = mkdtempSync(join(tmpdir(), "code-mode-sdkgen-emit-"));
    sdksDir = join(tmpRoot, "sdks");
    mkdirSync(sdksDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(tmpRoot, { recursive: true, force: true });
  });

  test("emits per-server file + shared _client.ts + _servers.json", async () => {
    const rep = await emitGeneratedSdks([buildResult("github")], {
      sdksDir,
      now: FIXED_NOW,
    });
    expect(rep.serverFiles).toHaveLength(1);
    expect(rep.serverFiles[0]!.server).toBe("github");

    const genDir = join(sdksDir, ".generated");
    expect(existsSync(join(genDir, "github.ts"))).toBe(true);
    expect(existsSync(join(genDir, "_client.ts"))).toBe(true);
    expect(existsSync(join(genDir, "_servers.json"))).toBe(true);

    const body = readFileSync(join(genDir, "github.ts"), "utf8");
    expect(body).toContain("@generated by code-mode sdk-gen");
    expect(body).toContain(`import { callTool } from "./_client.ts";`);
    expect(body).toContain("export interface CreateIssueArgs");
    expect(body).toContain("export async function createIssue");

    const registry = JSON.parse(readFileSync(join(genDir, "_servers.json"), "utf8"));
    expect(registry.github).toMatchObject({
      transport: "stdio",
      command: "bun",
      args: ["run", "server.ts"],
    });
  });

  test("wipes .generated/ before re-emitting; idempotent re-run is byte-stable", async () => {
    // Seed with a stale file to verify wipe.
    const genDir = join(sdksDir, ".generated");
    mkdirSync(genDir, { recursive: true });
    writeFileSync(join(genDir, "stale.ts"), "// stale");

    await emitGeneratedSdks([buildResult("github")], { sdksDir, now: FIXED_NOW });
    expect(existsSync(join(genDir, "stale.ts"))).toBe(false);
    const firstFiles = listGeneratedFiles(sdksDir);
    const firstBytes = firstFiles.map((p) => readFileSync(p));

    await emitGeneratedSdks([buildResult("github")], { sdksDir, now: FIXED_NOW });
    const secondFiles = listGeneratedFiles(sdksDir);
    const secondBytes = secondFiles.map((p) => readFileSync(p));

    expect(secondFiles).toEqual(firstFiles);
    for (let i = 0; i < firstBytes.length; i++) {
      expect(Buffer.compare(firstBytes[i]!, secondBytes[i]!)).toBe(0);
    }
  });

  test("records failing server in skipped, still emits shared client", async () => {
    const failing: IntrospectResult = {
      spec: {
        name: "broken",
        transport: "stdio",
        command: "does-not-exist",
        sourcePath: "/fake",
      },
      ok: false,
      tools: [],
      error: "introspect-error: spawn fail",
    };
    const rep = await emitGeneratedSdks([failing], { sdksDir, now: FIXED_NOW });
    expect(rep.serverFiles).toHaveLength(0);
    expect(rep.skipped).toHaveLength(1);
    expect(rep.skipped[0]!.server).toBe("broken");
    expect(existsSync(join(sdksDir, ".generated", "_client.ts"))).toBe(true);
  });

  test("slugifies server names with special characters", async () => {
    const result = buildResult("@scope/name with spaces");
    const rep = await emitGeneratedSdks([result], { sdksDir, now: FIXED_NOW });
    expect(rep.serverFiles[0]!.path).toContain("_scope_name_with_spaces.ts");
  });
});
