/**
 * Assemble + write the `.generated/` SDK directory for a workspace.
 *
 * Shape:
 *   .code-mode/sdks/.generated/
 *     _client.ts        — shared runtime invoker (one per workspace)
 *     <server>.ts       — one per server, imports `callTool` from _client
 *     _servers.json     — lightweight registry the client reads at runtime
 *                         to know how to spawn each server.
 *
 * Idempotency: we wipe `.generated/` before re-emitting, and file bodies are
 * deterministic modulo a timestamp header — tests pin both by passing a
 * stable `now` injection.
 */

import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { McpServerSpec } from "./config.ts";
import type { IntrospectResult } from "./introspect.ts";
import { generateToolCode, type CodegenOptions, type ToolCodegen } from "./codegen.ts";

export interface EmitOptions extends CodegenOptions {
  /** Absolute path to `<workspace>/.code-mode/sdks`. */
  sdksDir: string;
  /** Pinned timestamp for deterministic output. Defaults to now. */
  now?: () => Date;
}

export interface EmitReport {
  generatedDir: string;
  clientPath: string;
  serverFiles: Array<{ server: string; path: string; toolCount: number }>;
  skipped: Array<{ server: string; reason: string }>;
}

export async function emitGeneratedSdks(
  results: IntrospectResult[],
  opts: EmitOptions,
): Promise<EmitReport> {
  const nowFn = opts.now ?? (() => new Date());
  const generatedDir = join(opts.sdksDir, ".generated");

  // Wipe + recreate the `.generated/` directory. Derived state, so a clean
  // rebuild is cheaper than reasoning about partial cleanups.
  if (existsSync(generatedDir)) {
    rmSync(generatedDir, { recursive: true, force: true });
  }
  mkdirSync(generatedDir, { recursive: true });

  const serverFiles: EmitReport["serverFiles"] = [];
  const skipped: EmitReport["skipped"] = [];

  // Write one module per successfully-introspected server.
  const registry: Record<string, RegistryEntry> = {};
  for (const result of results) {
    if (!result.ok) {
      skipped.push({ server: result.spec.name, reason: result.error ?? "unknown" });
      continue;
    }
    if (result.tools.length === 0) {
      skipped.push({ server: result.spec.name, reason: "no tools/list returned" });
      continue;
    }
    const slug = toSlug(result.spec.name);
    const codegen = generateToolCode(result.tools, result.spec.name, opts);
    const body = assembleServerModule(result.spec.name, codegen, nowFn().toISOString());
    const outPath = join(generatedDir, `${slug}.ts`);
    writeFileSync(outPath, body);
    serverFiles.push({
      server: result.spec.name,
      path: outPath,
      toolCount: codegen.length,
    });
    registry[result.spec.name] = specToRegistry(result.spec);
  }

  // Shared client + registry — always written, even if no servers succeeded,
  // so downstream code can `import { callTool } from "./_client"` safely.
  const clientPath = join(generatedDir, "_client.ts");
  writeFileSync(clientPath, CLIENT_RUNTIME_SOURCE);
  writeFileSync(join(generatedDir, "_servers.json"), JSON.stringify(registry, null, 2));

  return { generatedDir, clientPath, serverFiles, skipped };
}

interface RegistryEntry {
  transport: "stdio" | "http";
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
}

function specToRegistry(spec: McpServerSpec): RegistryEntry {
  if (spec.transport === "stdio") {
    return {
      transport: "stdio",
      command: spec.command,
      args: spec.args,
      env: spec.env,
    };
  }
  return { transport: "http", url: spec.url };
}

/**
 * Emit a single server module. Layout:
 *   1. File-level JSDoc header — who generated it, when, from which server.
 *   2. Import of `callTool` from the shared runtime.
 *   3. Per-tool: args interface + result interface + async wrapper.
 */
function assembleServerModule(
  serverName: string,
  codegen: ToolCodegen[],
  generatedAt: string,
): string {
  const header =
    `/**\n` +
    ` * @generated by code-mode sdk-gen from MCP server "${serverName}" at ${generatedAt}.\n` +
    ` * DO NOT EDIT — this file is overwritten on every reindex.\n` +
    ` */\n`;

  const imports = `import { callTool } from "./_client.ts";\n`;

  const sections = codegen.map(
    (c) => `${c.inputDecl}\n\n${c.outputDecl}\n\n${c.fnDecl}`,
  );

  return `${header}${imports}\n${sections.join("\n\n")}\n`;
}

/**
 * Normalize a server name into a safe TS module filename. MCP names in the
 * wild include dashes, underscores, and occasionally slashes (for scoped
 * packages). We keep dashes and underscores, drop everything else.
 */
export function toSlug(name: string): string {
  return name.replace(/[^A-Za-z0-9_\-]/g, "_");
}

/**
 * Shared runtime helper. Kept as an embedded string so tests can assert on
 * byte-for-byte stability without reading an extra file from disk, and so we
 * don't ship a separate `.ts` asset to copy at emit time.
 *
 * The helper uses lazy imports to keep the emitted SDKs loadable even when the
 * script being typechecked doesn't actually invoke a tool call.
 */
const CLIENT_RUNTIME_SOURCE = `/**
 * @generated by code-mode sdk-gen — shared runtime invoker.
 * Spawns the relevant MCP server on demand, runs one tool call, returns the
 * parsed result. Cached per-process so repeated calls reuse the same
 * transport.
 *
 * DO NOT EDIT — overwritten on every reindex.
 */

import serversJson from "./_servers.json" with { type: "json" };

interface RegistryEntry {
  transport: "stdio" | "http";
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
}

const registry = serversJson as unknown as Record<string, RegistryEntry>;

interface ClientLike {
  callTool(params: { name: string; arguments?: Record<string, unknown> }): Promise<unknown>;
  close(): Promise<void>;
}

const cache = new Map<string, Promise<ClientLike>>();

async function getClient(server: string): Promise<ClientLike> {
  const existing = cache.get(server);
  if (existing) return existing;
  const entry = registry[server];
  if (!entry) throw new Error(\`[code-mode] unknown MCP server: \${server}\`);
  const p = (async (): Promise<ClientLike> => {
    const [{ Client }, stdio, http] = await Promise.all([
      import("@modelcontextprotocol/sdk/client/index.js"),
      import("@modelcontextprotocol/sdk/client/stdio.js"),
      import("@modelcontextprotocol/sdk/client/streamableHttp.js"),
    ]);
    const client = new Client(
      { name: "code-mode-runtime", version: "0.0.0" },
      { capabilities: {} },
    );
    let transport: unknown;
    if (entry.transport === "stdio") {
      if (!entry.command) throw new Error(\`[code-mode] stdio server \${server} missing command\`);
      transport = new stdio.StdioClientTransport({
        command: entry.command,
        args: entry.args ?? [],
        env: entry.env ? { ...(process.env as Record<string, string>), ...entry.env } : undefined,
        stderr: "inherit",
      });
    } else {
      if (!entry.url) throw new Error(\`[code-mode] http server \${server} missing url\`);
      transport = new http.StreamableHTTPClientTransport(new URL(entry.url));
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (client as any).connect(transport);
    return client as unknown as ClientLike;
  })();
  cache.set(server, p);
  return p;
}

export async function callTool<T = unknown>(
  server: string,
  tool: string,
  args: Record<string, unknown>,
): Promise<T> {
  const client = await getClient(server);
  const result = await client.callTool({ name: tool, arguments: args });
  return (result as { structuredContent?: unknown }).structuredContent as T ??
    (result as T);
}

export async function closeAll(): Promise<void> {
  const clients = Array.from(cache.values());
  cache.clear();
  await Promise.allSettled(
    clients.map(async (p) => {
      try {
        const c = await p;
        await c.close();
      } catch {
        /* best-effort */
      }
    }),
  );
}
`;

/**
 * Exported for tests: list every file currently under `.generated/`, so
 * idempotency tests can snapshot the full output directory.
 */
export function listGeneratedFiles(sdksDir: string): string[] {
  const generatedDir = join(sdksDir, ".generated");
  if (!existsSync(generatedDir)) return [];
  const out: string[] = [];
  const stack: string[] = [generatedDir];
  while (stack.length > 0) {
    const cur = stack.pop()!;
    for (const entry of readdirSync(cur, { withFileTypes: true })) {
      const full = join(cur, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile()) {
        out.push(full);
      }
    }
  }
  return out.sort();
}
