/**
 * Row-shaped TypeScript types for the code-mode SQLite schema.
 *
 * These mirror `src/db/migrations/001_initial.sql` 1:1. Keep them in sync when
 * adding a new migration.
 */

export type ScriptStatus = "ok" | "unusable";
export type SymbolScope = "stdlib" | "sdk" | "generated" | "script";
export type SdkScope = "stdlib" | "user" | "generated";
export type SymbolKind = "function" | "type" | "interface" | "class" | "const";

export interface ScriptRow {
  path: string;
  name: string;
  description: string | null;
  tags: string | null;          // JSON array string
  exports_json: string | null;  // serialized ExportInfo[]
  status: ScriptStatus;
  status_reason: string | null;
  runs: number;
  last_run: string | null;
  success_rate: number | null;
  indexed_at: string;
}

export interface SymbolRow {
  id: number;
  source_path: string;
  kind: SymbolKind | string;
  name: string;
  signature: string;
  jsdoc: string | null;
  scope: SymbolScope;
  sdk_name: string | null;
}

export interface SdkRow {
  name: string;
  scope: SdkScope;
  source_dir: string;
  symbol_count: number;
  last_indexed: string;
}

/**
 * Symbol insertion payload — shares shape with SymbolRow minus the autogenerated id.
 */
export type SymbolInsert = Omit<SymbolRow, "id">;
